package com.gomeo2o.service.account.rb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Dec 08 10:20:34 CST 2015
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://webservice.rb.gome.founder.com/", name = "AcceptBalanceTask")
@XmlSeeAlso({ObjectFactory.class})
public interface AcceptBalanceTask {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "acceptBalanceTask", targetNamespace = "http://webservice.rb.gome.founder.com/", className = "com.gomeo2o.service.account.rb.AcceptBalanceTask_Type")
    @WebMethod
    @ResponseWrapper(localName = "acceptBalanceTaskResponse", targetNamespace = "http://webservice.rb.gome.founder.com/", className = "com.gomeo2o.service.account.rb.AcceptBalanceTaskResponse")
    public com.gomeo2o.service.account.rb.RefundTaskReply acceptBalanceTask(
        @WebParam(name = "taskBean", targetNamespace = "")
        com.gomeo2o.service.account.rb.RefundBalanceTask taskBean
    );
}
