
package com.gomeo2o.service.account.rb;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Dec 08 10:20:34 CST 2015
 * Generated source version: 2.2.7
 * 
 */
 
public class AcceptBalanceTask_AcceptBalanceTaskImplPort_Server{

    protected AcceptBalanceTask_AcceptBalanceTaskImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new AcceptBalanceTaskImpl();
        String address = "http://rbuat.ds.gome.com.cn/ws/acceptBalanceTask";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new AcceptBalanceTask_AcceptBalanceTaskImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
