
/*
 * 
 */

package com.gomeo2o.service.account.rb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Dec 08 10:20:34 CST 2015
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "AcceptBalanceTaskImplService", 
                  wsdlLocation = "http://rbuat.ds.gome.com.cn/ws/acceptBalanceTask?wsdl",
                  targetNamespace = "http://impl.webservice.rb.gome.founder.com/") 
public class AcceptBalanceTaskImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.webservice.rb.gome.founder.com/", "AcceptBalanceTaskImplService");
    public final static QName AcceptBalanceTaskImplPort = new QName("http://impl.webservice.rb.gome.founder.com/", "AcceptBalanceTaskImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://rbuat.ds.gome.com.cn/ws/acceptBalanceTask?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://rbuat.ds.gome.com.cn/ws/acceptBalanceTask?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AcceptBalanceTaskImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AcceptBalanceTaskImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcceptBalanceTaskImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AcceptBalanceTask
     */
    @WebEndpoint(name = "AcceptBalanceTaskImplPort")
    public AcceptBalanceTask getAcceptBalanceTaskImplPort() {
        return super.getPort(AcceptBalanceTaskImplPort, AcceptBalanceTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcceptBalanceTask
     */
    @WebEndpoint(name = "AcceptBalanceTaskImplPort")
    public AcceptBalanceTask getAcceptBalanceTaskImplPort(WebServiceFeature... features) {
        return super.getPort(AcceptBalanceTaskImplPort, AcceptBalanceTask.class, features);
    }

}
