
package com.gomeo2o.service.account.rb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Dec 08 10:20:34 CST 2015
 * Generated source version: 2.2.7
 * 
 */

public final class AcceptBalanceTask_AcceptBalanceTaskImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.rb.gome.founder.com/", "AcceptBalanceTaskImplService");

    private AcceptBalanceTask_AcceptBalanceTaskImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AcceptBalanceTaskImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AcceptBalanceTaskImplService ss = new AcceptBalanceTaskImplService(wsdlURL, SERVICE_NAME);
        AcceptBalanceTask port = ss.getAcceptBalanceTaskImplPort();  
        
        {
        System.out.println("Invoking acceptBalanceTask...");
        com.gomeo2o.service.account.rb.RefundBalanceTask _acceptBalanceTask_taskBean = null;
        com.gomeo2o.service.account.rb.RefundTaskReply _acceptBalanceTask__return = port.acceptBalanceTask(_acceptBalanceTask_taskBean);
        System.out.println("acceptBalanceTask.result=" + _acceptBalanceTask__return);


        }

        System.exit(0);
    }

}
